# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  imageName: 'portal-ui-swathi:$(Build.BuildId)'
  dockerId: bluef5
  dockerPassword: 72TolszvZFVn373zKfd8SIzs2o=qlnpg
steps:
- script: |
<<<<<<< HEAD
    docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $pswd $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: $(dockerPassword)
  displayName: 'Build and push Docker image'
=======
    npm install
    npm run build
    npm test
  displayName: 'npm install and build  and run unit testing'

>>>>>>> 3f0a821ecdfa73e748f320077855dbdf8d83e595
